# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    restart: always
    container_name: gundam_db
    command: 
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - 3306:3306
